Add multiarch support (again) and update to 17.06.0-ce-rc2

diff --git a/17.05/Dockerfile b/17.05/Dockerfile
--- a/17.05/Dockerfile
+++ b/17.05/Dockerfile
@@ -6,6 +6,8 @@ RUN apk add --no-cache \
 ENV DOCKER_CHANNEL edge
 ENV DOCKER_VERSION 17.05.0-ce
 # TODO ENV DOCKER_SHA256
+# https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
+# (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
 
 RUN set -ex; \
 # why we use "curl" instead of "wget":
@@ -16,14 +18,30 @@ RUN set -ex; \
 		curl \
 		tar \
 	; \
-	curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz"; \
+	\
+# this "case" statement is generated via "update.sh"
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64) dockerArch='x86_64' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	\
+	if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}-${dockerArch}.tgz"; then \
+		if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+			echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+			exit 1; \
+		fi; \
+	fi; \
+	\
 	tar --extract \
 		--file docker.tgz \
 		--strip-components 1 \
 		--directory /usr/local/bin/ \
 	; \
 	rm docker.tgz; \
+	\
 	apk del .fetch-deps; \
+	\
 	dockerd -v; \
 	docker -v
 
