Add experimental armhf support via "case" on "apk --print-arch"

diff --git a/17.03/Dockerfile b/17.03/Dockerfile
--- a/17.03/Dockerfile
+++ b/17.03/Dockerfile
@@ -7,16 +7,25 @@ RUN apk add --no-cache \
 
 ENV DOCKER_BUCKET get.docker.com
 ENV DOCKER_VERSION 17.03.1-ce
-ENV DOCKER_SHA256 820d13b5699b5df63f7032c8517a5f118a44e2be548dd03271a86656a544af55
+ENV DOCKER_SHA256_x86_64 820d13b5699b5df63f7032c8517a5f118a44e2be548dd03271a86656a544af55
+ENV DOCKER_SHA256_armel f05c733c22915b0c26d8b0390b26a026b33aaf7593d15475a6f86e1bbe1ddbe2
 
-RUN set -x \
-	&& curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
-	&& echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
-	&& tar -xzvf docker.tgz \
-	&& mv docker/* /usr/local/bin/ \
-	&& rmdir docker \
-	&& rm docker.tgz \
-	&& docker -v
+RUN set -ex; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64) dockerArch=x86_64 ;; \
+		armhf) dockerArch=armel ;; \
+		*) echo >&2 "error: unknown Docker static binary arch $apkArch"; exit 1 ;; \
+	esac; \
+	curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/${dockerArch}/docker-${DOCKER_VERSION}.tgz" -o docker.tgz; \
+# /bin/sh doesn't support ${!...} :(
+	sha256="DOCKER_SHA256_${dockerArch}"; sha256="$(eval "echo \$${sha256}")"; \
+	echo "${sha256} *docker.tgz" | sha256sum -c -; \
+	tar -xzvf docker.tgz; \
+	mv docker/* /usr/local/bin/; \
+	rmdir docker; \
+	rm docker.tgz; \
+	docker -v
 
 COPY docker-entrypoint.sh /usr/local/bin/
 
diff --git a/17.04/Dockerfile b/17.04/Dockerfile
--- a/17.04/Dockerfile
+++ b/17.04/Dockerfile
@@ -7,16 +7,25 @@ RUN apk add --no-cache \
 
 ENV DOCKER_BUCKET get.docker.com
 ENV DOCKER_VERSION 17.04.0-ce
-ENV DOCKER_SHA256 c52cff62c4368a978b52e3d03819054d87bcd00d15514934ce2e0e09b99dd100
+ENV DOCKER_SHA256_x86_64 c52cff62c4368a978b52e3d03819054d87bcd00d15514934ce2e0e09b99dd100
+ENV DOCKER_SHA256_armel 9b7df7dc02f620748657d3f599a9701c35f7b0b3d0acbc7fd324126ba5f6c4e9
 
-RUN set -x \
-	&& curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
-	&& echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
-	&& tar -xzvf docker.tgz \
-	&& mv docker/* /usr/local/bin/ \
-	&& rmdir docker \
-	&& rm docker.tgz \
-	&& docker -v
+RUN set -ex; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64) dockerArch=x86_64 ;; \
+		armhf) dockerArch=armel ;; \
+		*) echo >&2 "error: unknown Docker static binary arch $apkArch"; exit 1 ;; \
+	esac; \
+	curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/${dockerArch}/docker-${DOCKER_VERSION}.tgz" -o docker.tgz; \
+# /bin/sh doesn't support ${!...} :(
+	sha256="DOCKER_SHA256_${dockerArch}"; sha256="$(eval "echo \$${sha256}")"; \
+	echo "${sha256} *docker.tgz" | sha256sum -c -; \
+	tar -xzvf docker.tgz; \
+	mv docker/* /usr/local/bin/; \
+	rmdir docker; \
+	rm docker.tgz; \
+	docker -v
 
 COPY docker-entrypoint.sh /usr/local/bin/
 
